spring:
  application.name: moira

  profiles:
    active: ${STAGE}

  jpa:
    open-in-view: false

server:
  servlet:
    session:
      cookie:
        path: /
        name: sid
        http-only: true
        secure: true
    timeout: 3600
